import type { EditionNarrativeItem } from "@/lib/types";

export function buildBriefingPrompt(items: EditionNarrativeItem[], timezone: string, targetReadingMinutes: number, language: string = "French"): string {
  const stories = items
    .map((item, index) =>
      [
        `${index + 1}. [#${index + 1}] ${item.title} — ${item.feed}`,
        `   URL: ${item.url}`,
        `   Published: ${item.publishedAt}`,
        `   Abstract: ${item.summary.abstract}`,
        `   Bullets: ${item.summary.bullets.join(" • ")}`
      ].join("\n")
    )
    .join("\n");

  return [
    `You are a skilled ${language} journalist writing a morning briefing in the style of an analytical newsletter for informed readers.`,
    "Your task is to weave a narrative that explains significance, causal context and emerging dynamics – never a flat list of headlines.",
    "",
    "Style and approach:",
    "- Crisp, high‑signal prose; strictly neutral (no partisan or emotive framing).",
    "- Cohesion: each paragraph should advance the previous one (avoid thematic whiplash).",
    "- Surface connections: shared drivers, structural forces, feedback loops, contrasts.",
    "- Avoid filler, rhetorical questions or generic transitional phrases.",
    "- Target: depth over breadth; omit trivia to preserve analytical density.",
    "",
    "Narrative structure (DO THIS PRECISELY):",
    "- Overview: 2–3 paragraphs synthesising dominant cross‑source themes and linking causes to consequences.",
    "- Background: 1 paragraph giving historical / structural context (precedents, regulatory / geopolitical / economic backdrop). Not a recap of overview.",
    "- Analysis: 1 paragraph extracting implications, tensions, risks, strategic shifts, unanswered questions. No speculation stated as fact.",
    "",
    "Citation requirements (STRICT):",
    "- EVERY paragraph (overview, background, analysis) cites ≥2 distinct sources (if available).",
    "- First mention: [Exact Article Title](URL) (FeedName). Later references may use index tag [#N].",
    "- Coverage: ≥70% of all source articles cited across overview+background+analysis (timeline alone does not count).",
    "- Each of overview/background/analysis must cite ≥3 distinct sources unless fewer exist globally.",
    "- Integrate any unused sources naturally before finishing analysis (never a dangling leftover list).",
    "- NEVER fabricate titles, feeds, URLs, statistics, quotes or chronology.",
    "",
    "Analytical discipline:",
    "- Explain WHY developments matter (mechanism, scale, stakeholders) not just THAT they occurred.",
    "- Prefer specific signals (figures, policy moves, concrete actions) over vague adjectives.",
    "- Highlight contrasts (divergent strategies, conflicting data) when they sharpen understanding.",
    "",
    "Link placement:",
    "- Embed links inline supporting claims; avoid stacked parenthetical lists.",
    "- Do not repeat identical link/title patterns redundantly.",
    "",
    `Reading time goal ≈ ${targetReadingMinutes} minutes (~${Math.round(targetReadingMinutes * 200)} words) is guidance ONLY. Do NOT pad or trim to force length – natural length prevails.`,
    `Respond entirely in ${language}.`,
    "",
    "Reply in JSON with the structure:",
    "{",
    '  "overview": "<2-3 paragraphs – each with ≥2 cited sources>",',
    '  "background": "<1 paragraph – ≥2 cited sources>",',
    '  "analysis": "<1 paragraph – ≥2 cited sources>",',
    '  "timeline": [',
    '    {"title": "...", "summary": "...", "date": "YYYY-MM-DD", "source": "FeedName", "url": "..."}',
    "  ],",
    `  "fastFacts": ["short fact in ${language}", "..."],`,
    '  "furtherReading": [ {"title": "...", "url": "...", "note": "optional context"} ],',
    `  "readingMinutes": <integer around ${targetReadingMinutes}>,`,
    '  "wordCount": <integer>',
    "}",
    "",
    "Requirements:",
    "- Timeline: 4\u20137 key events (oldest first) \u2013 strictly factual, neutral, concise.",
    `- Fast facts: punchy, \u2264140 chars each, in ${language}.`,
    `- Further reading: 3\u20135 high\u2011value links w/ succinct ${language} notes (distinct sources if possible).`,
    "- Word count: approximate overview+background+analysis+timeline summaries.",
    "- Timezone: " + timezone,
    "- No artificial truncation: never cut mid\u2011sentence to hit length targets.",
    "- No ellipses ('...' or '\u2026') purely to signal omitted text or trimming.",
    "- Finish the sentence: if guidance length exceeded, complete current sentence rather than chopping.",
    "- Never add placeholder bullets or filler to adjust perceived length.",
    "",
    "Source stories (indexed):",
    stories || "No sources provided."
  ].join("\n");
}
